[package]
name = "coap"
version = "0.1.0"
edition = "2021"

[dependencies]
edhoc-rs = { path = "../../lib", features = [ "crypto-hacspec" ] }
hexlit = "0.5.3"
coap = { version = "0.13" }
coap-lite = { version = "0.11.3" }
