[package]
name = "coap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "coapclient"
path = "src/coapclient.rs"

[[bin]]
name = "coapserver"
path = "src/coapserver.rs"

[dependencies]
edhoc-rs = { path = "../../lib", features = [ "hacspec-native" ] }
coap = { version = "0.12" }
coap-lite = { version = "0.9.1" }
