[workspace]

members = [
	"lib",
	"hacspec",
	"crypto",
	"examples/coap",
]

[patch.crates-io]
hacspec-lib = { git = "https://github.com/malishav/hacspec", branch = "aesccm" }
hacspec-p256 = { git = "https://github.com/malishav/hacspec", branch = "aesccm" }
hacspec-hkdf = { git = "https://github.com/malishav/hacspec", branch = "aesccm" }
hacspec-sha256 = { git = "https://github.com/malishav/hacspec", branch = "aesccm" }
hacspec-aes = { git = "https://github.com/malishav/hacspec", branch = "aesccm" }
hacspec-aes-ccm = { git = "https://github.com/malishav/hacspec", branch = "aesccm" }
