[package]
name = "edhoc"
version = "0.1.0"
edition = "2021"
authors = ["Mališa Vučinić <malisa.vucinic@inria.fr>"]
license = "BSD"
description = "EDHOC implementation"

[dependencies]
coap = "0.11.3"
hex-literal = { version = "0.3.4" }
hacspec-lib = { path = "../hacspec/lib" }
hacspec-p256 = { path = "../hacspec/examples/p256" }
hacspec-hkdf = { path = "../hacspec/examples/hkdf" }
hacspec-sha256 = { path = "../hacspec/examples/sha256" }
hacspec-aes = { path = "../hacspec/examples/aes" }
hacspec-aes-ccm = { path = "../hacspec/examples/aes-ccm" }

