[package]
name = "edhoc"
version = "0.1.0"
edition = "2021"
authors = ["Mališa Vučinić <malisa.vucinic@inria.fr>"]
license = "BSD"
description = "EDHOC implementation"

[dependencies]
hex-literal = { version = "0.3.4" }
hacspec-lib = { path = "../../../Software/hacspec/lib" }
hacspec-p256 = { path = "../../../Software/hacspec/examples/p256" }
hacspec-hkdf = { path = "../../../Software/hacspec/examples/hkdf" }
hacspec-sha256 = { path = "../../../Software/hacspec/examples/sha256" }


