[package]
name = "edhoc"
version = "0.1.0"
edition = "2021"
authors = ["Mališa Vučinić <malisa.vucinic@inria.fr>"]
license = "BSD"
description = "EDHOC implementation"

[dependencies]
hacspec-p256 = { path = "../../../Software/hacspec/examples/p256" }

