[package]
name = "lakers-ead-none"
version.workspace = true
edition = "2021"
authors = ["Geovane Fedrecheski <geonnave@gmail.com>"]
license.workspace = true
description = "EDHOC EAD none (just a placeholder)"
repository.workspace = true

[dependencies]
lakers-shared.workspace = true
