[package]
name = "edhoc-ead"
version.workspace = true
edition = "2021"
authors = ["Geovane Fedrecheski <geonnave@gmail.com>"]
license = "BSD"
description = "EDHOC EAD library dispatch crate"

[dependencies]
edhoc-consts.workspace = true

edhoc-ead-none = { workspace = true, optional = true }
edhoc-ead-zeroconf = { workspace = true, optional = true }

[features]
default = [ "ead-none" ]
ead-none = [ "edhoc-ead-none" ]
ead-zeroconf = [ "edhoc-ead-zeroconf" ]
