[package]
name = "lakers-shared"
version.workspace = true
edition = "2021"
authors = ["Mališa Vučinić <malisa.vucinic@inria.fr>"]
license.workspace = true
description = "EDHOC crypto library constants crate"
repository.workspace = true
# It's implied, but still better for consistency to have it explicit.
readme.workspace = true

[dependencies]
# pyo3 = { version = "0.20.2", features = ["extension-module"], optional = true }
pyo3 = { git = "https://github.com/PyO3/pyo3.git", features = ["extension-module"], optional = true }

[dev-dependencies]
hexlit = "0.5.3"

[features]
default = [  ]
python-traits = ["pyo3"]
