[package]
name = "edhoc-consts"
version = "0.1.0"
edition = "2021"
authors = ["Mališa Vučinić <malisa.vucinic@inria.fr>"]
license = "BSD"
description = "EDHOC crypto library constants crate"

[dev-dependencies]
hexlit = "0.5.3"
