[package]
name = "edhoc-consts"
version.workspace = true
edition = "2021"
authors = ["Mališa Vučinić <malisa.vucinic@inria.fr>"]
license.workspace = true
description = "EDHOC crypto library constants crate"
repository.workspace = true

[dev-dependencies]
hexlit = "0.5.3"
