# call with:
# cbindgen --config consts/cbindgen.toml --crate edhoc-consts --output edhoc_consts.h -vv

language = "C"

[export]
include = ["State", "EdhocMessageBuffer"]

[parse.expand]
crates = ["edhoc-consts"]
default_features = false
features = ["rust"]
