name: Rust

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build with PSA crypto backend
      run: cargo build --package edhoc-rs --package edhoc-hacspec --package edhoc-crypto --no-default-features --features="hacspec-psa"
    - name: Run tests with PSA crypto backend
      run: cargo test --package edhoc-rs --package edhoc-hacspec --package edhoc-crypto --no-default-features --features="hacspec-psa" --no-fail-fast --verbose
    - name: Install thumbv7m-none-eabi and thumbv7em-none-eabihf rust target support
      run: rustup target add thumbv7m-none-eabi && rustup target add thumbv7em-none-eabihf
    - name: Build Rust version with PSA crypto backend
      run: cargo build --package edhoc-rs --features="rust-native" --package edhoc-crypto --no-default-features --features="psa-rust"
    - name: Install arm gcc
      run: sudo apt-get -y update && sudo apt-get -y install gcc-arm-none-eabi
    - name: Install QEMU ARM emulator
      run: sudo apt-get -y install qemu-system-arm
    - name: Build no_std edhoc-rs
      run: cargo build --target="thumbv7m-none-eabi" --features="hacspec-cc2538" --no-default-features --package edhoc-rs
    - name: Build examples/edhoc-rs-no_std cc2538
      run: cd examples/edhoc-rs-no_std && cargo build
    - name: Build examples/edhoc-rs-no_std psa
      run: cd examples/edhoc-rs-no_std && cargo build --no-default-features --features=psa --release
    - name: Run tests in QEMU
      run: cd examples/edhoc-rs-no_std && cargo run --no-default-features --features=psa --release
    - name: Build examples/edhoc-rs-no_std psa nrf52840
      run: cd examples/edhoc-rs-no_std && cargo build --target="thumbv7em-none-eabihf" --no-default-features --features="psa, nrf52840" --release
    - name: Build examples/edhoc-rs-no_std cryptocell310 nrf52840
      run: cd examples/edhoc-rs-no_std && cargo build --target="thumbv7em-none-eabihf" --no-default-features --features="cryptocell310, nrf52840"
